// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartKitchen.Infrastructure;

#nullable disable

namespace SmartKitchen.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("SmartKitchen.Domain.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Nudeln",
                            Name = "Spaghetti",
                            PricePerUnit = 0.003m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Fleisch",
                            Name = "Hackfleisch",
                            PricePerUnit = 0.009m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Soßen",
                            Name = "Tomatensoße",
                            PricePerUnit = 0.004m,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Gemüse",
                            Name = "Zwiebel",
                            PricePerUnit = 0.30m,
                            Unit = "Stück"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Gemüse",
                            Name = "Knoblauch",
                            PricePerUnit = 0.15m,
                            Unit = "Zehe"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Öle",
                            Name = "Olivenöl",
                            PricePerUnit = 0.01m,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Käse",
                            Name = "Parmesan",
                            PricePerUnit = 0.02m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Fleisch",
                            Name = "Hähnchenbrust",
                            PricePerUnit = 0.012m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Getreide",
                            Name = "Reis",
                            PricePerUnit = 0.002m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Gemüse",
                            Name = "Brokkoli",
                            PricePerUnit = 0.005m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Milchprodukte",
                            Name = "Sahne",
                            PricePerUnit = 0.003m,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Milchprodukte",
                            Name = "Butter",
                            PricePerUnit = 0.008m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Backen",
                            Name = "Mehl",
                            PricePerUnit = 0.001m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Milchprodukte",
                            Name = "Eier",
                            PricePerUnit = 0.25m,
                            Unit = "Stück"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Gewürze",
                            Name = "Salz",
                            PricePerUnit = 0.001m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Gewürze",
                            Name = "Pfeffer",
                            PricePerUnit = 0.05m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Gemüse",
                            Name = "Paprika",
                            PricePerUnit = 0.80m,
                            Unit = "Stück"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Gemüse",
                            Name = "Champignons",
                            PricePerUnit = 0.006m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Gemüse",
                            Name = "Kartoffeln",
                            PricePerUnit = 0.002m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Fisch",
                            Name = "Lachs",
                            PricePerUnit = 0.025m,
                            Unit = "g"
                        });
                });

            modelBuilder.Entity("SmartKitchen.Domain.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentStock")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimumStock")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStock = 1000m,
                            ExpiryDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 1,
                            LastUpdated = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumStock = 500m
                        },
                        new
                        {
                            Id = 2,
                            CurrentStock = 500m,
                            ExpiryDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 6,
                            LastUpdated = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumStock = 200m
                        },
                        new
                        {
                            Id = 3,
                            CurrentStock = 2000m,
                            ExpiryDate = new DateTime(2027, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 9,
                            LastUpdated = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumStock = 500m
                        },
                        new
                        {
                            Id = 4,
                            CurrentStock = 500m,
                            IngredientId = 15,
                            LastUpdated = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumStock = 100m
                        },
                        new
                        {
                            Id = 5,
                            CurrentStock = 100m,
                            IngredientId = 16,
                            LastUpdated = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumStock = 50m
                        },
                        new
                        {
                            Id = 6,
                            CurrentStock = 2000m,
                            ExpiryDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 13,
                            LastUpdated = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumStock = 500m
                        },
                        new
                        {
                            Id = 7,
                            CurrentStock = 200m,
                            ExpiryDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 12,
                            LastUpdated = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumStock = 100m
                        },
                        new
                        {
                            Id = 8,
                            CurrentStock = 12m,
                            ExpiryDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IngredientId = 14,
                            LastUpdated = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            MinimumStock = 6m
                        });
                });

            modelBuilder.Entity("SmartKitchen.Domain.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("SmartKitchen.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SmartKitchen.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("RecipeId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SmartKitchen.Domain.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Hauptgericht",
                            CookTimeMinutes = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Klassische italienische Pasta mit reichhaltiger Fleischsoße",
                            Difficulty = "Einfach",
                            EstimatedCost = 8.50m,
                            ImageUrl = "",
                            Instructions = "1. Zwiebel und Knoblauch fein hacken und in Olivenöl anbraten.\n2. Hackfleisch hinzufügen und krümelig braten.\n3. Tomatensoße hinzugeben und 20 Minuten köcheln lassen.\n4. Spaghetti nach Packungsanleitung kochen.\n5. Soße über die Pasta geben und mit Parmesan servieren.",
                            Name = "Spaghetti Bolognese",
                            PrepTimeMinutes = 15,
                            Servings = 4
                        },
                        new
                        {
                            Id = 2,
                            Category = "Hauptgericht",
                            CookTimeMinutes = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gesunde Bowl mit zartem Hähnchen, Reis und frischem Gemüse",
                            Difficulty = "Einfach",
                            EstimatedCost = 6.00m,
                            ImageUrl = "",
                            Instructions = "1. Reis nach Packungsanleitung kochen.\n2. Hähnchenbrust in Streifen schneiden und würzen.\n3. Hähnchen in der Pfanne goldbraun braten.\n4. Brokkoli dampfgaren.\n5. Alles in einer Bowl anrichten.",
                            Name = "Hähnchen-Reis-Bowl",
                            PrepTimeMinutes = 10,
                            Servings = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Hauptgericht",
                            CookTimeMinutes = 35,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cremiges Risotto mit frischen Champignons und Parmesan",
                            Difficulty = "Mittel",
                            EstimatedCost = 7.00m,
                            ImageUrl = "",
                            Instructions = "1. Champignons in Scheiben schneiden.\n2. Zwiebel fein hacken und in Butter anschwitzen.\n3. Reis hinzufügen und glasig rühren.\n4. Nach und nach warme Brühe hinzufügen.\n5. Champignons und Parmesan unterrühren.",
                            Name = "Pilzrisotto",
                            PrepTimeMinutes = 10,
                            Servings = 4
                        },
                        new
                        {
                            Id = 4,
                            Category = "Hauptgericht",
                            CookTimeMinutes = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gebratener Lachs auf einem Bett aus Kartoffelpüree",
                            Difficulty = "Mittel",
                            EstimatedCost = 12.00m,
                            ImageUrl = "",
                            Instructions = "1. Kartoffeln schälen und kochen.\n2. Lachs würzen und in der Pfanne braten.\n3. Kartoffeln stampfen mit Butter und Sahne.\n4. Lachs auf dem Püree anrichten.\n5. Mit frischen Kräutern garnieren.",
                            Name = "Lachs mit Kartoffeln",
                            PrepTimeMinutes = 20,
                            Servings = 2
                        },
                        new
                        {
                            Id = 5,
                            Category = "Hauptgericht",
                            CookTimeMinutes = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bunte Gemüsepfanne mit Paprika, Champignons und Brokkoli",
                            Difficulty = "Einfach",
                            EstimatedCost = 5.00m,
                            ImageUrl = "",
                            Instructions = "1. Alles Gemüse waschen und schneiden.\n2. Olivenöl in einer großen Pfanne erhitzen.\n3. Gemüse nach Garzeit sortiert hinzufügen.\n4. Mit Salz, Pfeffer und Gewürzen abschmecken.\n5. Optional mit Reis servieren.",
                            Name = "Gemüsepfanne",
                            PrepTimeMinutes = 15,
                            Servings = 4
                        },
                        new
                        {
                            Id = 6,
                            Category = "Frühstück",
                            CookTimeMinutes = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fluffige Pfannkuchen – perfekt zum Frühstück oder als Dessert",
                            Difficulty = "Einfach",
                            EstimatedCost = 3.00m,
                            ImageUrl = "",
                            Instructions = "1. Mehl, Eier, Milch und eine Prise Salz verrühren.\n2. Butter in einer Pfanne schmelzen.\n3. Teig portionsweise in die Pfanne geben.\n4. Von beiden Seiten goldbraun backen.\n5. Mit Zucker, Zimt oder Früchten servieren.",
                            Name = "Pfannkuchen",
                            PrepTimeMinutes = 10,
                            Servings = 4
                        });
                });

            modelBuilder.Entity("SmartKitchen.Domain.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500m,
                            IngredientId = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 400m,
                            IngredientId = 2,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 500m,
                            IngredientId = 3,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2m,
                            IngredientId = 4,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 3m,
                            IngredientId = 5,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 30m,
                            IngredientId = 6,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 50m,
                            IngredientId = 7,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 300m,
                            IngredientId = 8,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Amount = 200m,
                            IngredientId = 9,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Amount = 200m,
                            IngredientId = 10,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Amount = 20m,
                            IngredientId = 6,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 12,
                            Amount = 300m,
                            IngredientId = 9,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 13,
                            Amount = 250m,
                            IngredientId = 18,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 14,
                            Amount = 1m,
                            IngredientId = 4,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 15,
                            Amount = 40m,
                            IngredientId = 12,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 16,
                            Amount = 60m,
                            IngredientId = 7,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 17,
                            Amount = 400m,
                            IngredientId = 20,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 18,
                            Amount = 600m,
                            IngredientId = 19,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 19,
                            Amount = 30m,
                            IngredientId = 12,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 20,
                            Amount = 100m,
                            IngredientId = 11,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 21,
                            Amount = 2m,
                            IngredientId = 17,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 22,
                            Amount = 200m,
                            IngredientId = 18,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 23,
                            Amount = 200m,
                            IngredientId = 10,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 24,
                            Amount = 1m,
                            IngredientId = 4,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 25,
                            Amount = 30m,
                            IngredientId = 6,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 26,
                            Amount = 250m,
                            IngredientId = 13,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 27,
                            Amount = 3m,
                            IngredientId = 14,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 28,
                            Amount = 30m,
                            IngredientId = 12,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 29,
                            Amount = 5m,
                            IngredientId = 15,
                            RecipeId = 6
                        });
                });

            modelBuilder.Entity("SmartKitchen.Domain.ShoppingListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("SmartKitchen.Domain.InventoryItem", b =>
                {
                    b.HasOne("SmartKitchen.Domain.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SmartKitchen.Domain.MealPlan", b =>
                {
                    b.HasOne("SmartKitchen.Domain.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartKitchen.Domain.OrderItem", b =>
                {
                    b.HasOne("SmartKitchen.Domain.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartKitchen.Domain.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartKitchen.Domain.RecipeIngredient", b =>
                {
                    b.HasOne("SmartKitchen.Domain.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartKitchen.Domain.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartKitchen.Domain.ShoppingListItem", b =>
                {
                    b.HasOne("SmartKitchen.Domain.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SmartKitchen.Domain.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("SmartKitchen.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SmartKitchen.Domain.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
